FROM golang:1.26 AS build-stage
WORKDIR /app

COPY go.mod ./
COPY cmd ./cmd

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/client ./cmd/client

FROM gcr.io/distroless/static-debian12

COPY --from=build-stage /out/client /client
ENTRYPOINT ["/client"]
